# Generated by Django 5.0.7 on 2024-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('qualifications', models.TextField()),
                ('teacher_status', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField()),
                ('teacher_photo', models.ImageField(upload_to='teacher_photos')),
            ],
        ),
    ]
