# Generated by Django 5.0.7 on 2024-07-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('course_credits', models.IntegerField()),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('course_status', models.CharField(max_length=20)),
                ('course_location', models.CharField(max_length=50)),
                ('course_time', models.CharField(max_length=20)),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teacher.teacher')),
                ('ourse_students', models.ManyToManyField(related_name='courses', to='student.student')),
            ],
        ),
    ]
