# Generated by Django 5.0.7 on 2024-08-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ourse_students',
            new_name='course_students',
        ),
    ]
