# Generated by Django 5.0.7 on 2024-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_project',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.TextField()),
                ('class_start_date', models.DateField()),
                ('class_end_date', models.DateField()),
                ('class_capacity', models.IntegerField()),
                ('class_status', models.CharField(max_length=20)),
                ('class_location', models.CharField(max_length=50)),
                ('class_time', models.CharField(max_length=20)),
                ('class_students', models.ManyToManyField(related_name='class_projects', to='student.student')),
            ],
        ),
    ]
