# Generated by Django 5.0.7 on 2024-08-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_ourse_students_course_course_students'),
        ('student', '0002_rename_student_id_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parentContact',
            new_name='parent_contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parentName',
            new_name='parent_name',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
